# Configuration file for php.civrays.com apache virtualhost

<VirtualHost *:80>

    ServerName php.civrays.com
    DocumentRoot /var/www/php

</VirtualHost>

<Directory "/var/www/php">

    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
    DirectoryIndex index.html

</Directory>
